# Registers (or re-registers) the hourly "Lattice MCP Cleanup" scheduled task.
# Uses S4U + a dedicated wscript .vbs (style 0) so no console flashes.
# Must run elevated: Unregister without re-register rights can delete the task.
#
# Usage:
#   pwsh -File scripts/install-mcp-cleanup-scheduled-task.ps1
#   pwsh -File scripts/install-mcp-cleanup-scheduled-task.ps1 -Uninstall

param(
  [switch]$DryRun,
  [switch]$Uninstall,
  [string]$TaskName = 'Lattice MCP Cleanup',
  [string]$RepoRoot = (Split-Path $PSScriptRoot -Parent)
)

$ErrorActionPreference = 'Stop'

$elevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).
  IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $elevated) {
  Write-Host 'X  Run elevated (Administrator). Unregister is irreversible without re-register rights.' -ForegroundColor Red
  exit 1
}

$installDir = Join-Path $env:USERPROFILE '.local\bin'
$installedWrapper = Join-Path $installDir 'lattice-mcp-cleanup.ps1'
$installedVbs = Join-Path $installDir 'task-lattice-mcp-cleanup.vbs'

if ($Uninstall) {
  Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
  Write-Host "Unregistered task: $TaskName"
  exit 0
}

$repoScript = Join-Path $RepoRoot 'mcp\cleanup-processes.mjs'
if (-not (Test-Path -LiteralPath $repoScript)) {
  throw "cleanup-processes.mjs not found under $RepoRoot"
}

New-Item -ItemType Directory -Force -Path $installDir | Out-Null

$repoEsc = $repoScript.Replace("'", "''")
$installedBody = @"
# Installed by lattice scripts/install-mcp-cleanup-scheduled-task.ps1
param([switch]`$DryRun)
`$ErrorActionPreference = 'SilentlyContinue'
`$repoScript = '$repoEsc'
`$node = (Get-Command node.exe -ErrorAction SilentlyContinue).Source
`$logDir = Join-Path `$env:USERPROFILE '.local\state\lattice'
`$logPath = Join-Path `$logDir 'mcp-cleanup.log'
New-Item -ItemType Directory -Force -Path `$logDir | Out-Null
if (-not `$node) {
  "[`$(Get-Date -Format o)] skipped: node.exe not found" | Add-Content -Path `$logPath
  exit 0
}
if (-not (Test-Path -LiteralPath `$repoScript)) {
  "[`$(Get-Date -Format o)] skipped: missing `$repoScript" | Add-Content -Path `$logPath
  exit 0
}
`$nodeArgs = @(`$repoScript)
if (`$DryRun) { `$nodeArgs += '--dry-run' }
if (-not `$env:LATTICE_MCP_CLEANUP_CPU_SAMPLE_MS) { `$env:LATTICE_MCP_CLEANUP_CPU_SAMPLE_MS = '1200' }
if (-not `$env:LATTICE_MCP_CLEANUP_SEMBLE_GRACE_HOURS) { `$env:LATTICE_MCP_CLEANUP_SEMBLE_GRACE_HOURS = '1.0' }
if (-not `$env:LATTICE_MCP_CLEANUP_PLAYWRIGHT_GRACE_HOURS) { `$env:LATTICE_MCP_CLEANUP_PLAYWRIGHT_GRACE_HOURS = '1.0' }
`$output = & `$node @nodeArgs 2>&1
`$exitCode = `$LASTEXITCODE
if (`$output) {
  "[`$(Get-Date -Format o)] exit=`$exitCode" | Add-Content -Path `$logPath
  `$output | Add-Content -Path `$logPath
}
exit 0
"@
Set-Content -LiteralPath $installedWrapper -Value $installedBody -Encoding UTF8

$pwsh = (Get-Command pwsh.exe -ErrorAction SilentlyContinue).Source
if (-not $pwsh) { $pwsh = (Get-Command powershell.exe).Source }

$vbsBody = @"
' Auto-generated by install-mcp-cleanup-scheduled-task.ps1
Option Explicit
Dim shell, cmd, rc
Set shell = CreateObject("WScript.Shell")
cmd = """$pwsh""" & _
      " -NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass" & _
      " -File ""$installedWrapper"""
rc = shell.Run(cmd, 0, True)
WScript.Quit rc
"@
Set-Content -LiteralPath $installedVbs -Value $vbsBody -Encoding ASCII

$wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'
$arg = "//nologo //B `"$installedVbs`""
if ($DryRun) {
  # Dry-run flag is on the ps1; regenerate VBS with -DryRun if requested
  $vbsBody = $vbsBody -replace '-File ""([^"]+)""', '-File ""$1"" -DryRun'
  Set-Content -LiteralPath $installedVbs -Value $vbsBody -Encoding ASCII
}

Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

$action = New-ScheduledTaskAction -Execute $wscript -Argument $arg
$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).Date.AddMinutes(5) `
  -RepetitionInterval (New-TimeSpan -Hours 1) `
  -RepetitionDuration (New-TimeSpan -Days 3650)
$set = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
  -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes 5) -Hidden
$pri = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType S4U -RunLevel Limited

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
  -Settings $set -Principal $pri `
  -Description 'Hourly fail-open cleanup for stale Semble/Playwright MCP helper processes via Lattice.' | Out-Null

$t = Get-ScheduledTask -TaskName $TaskName
Write-Host "Registered $TaskName  State=$($t.State)  Logon=$($t.Principal.LogonType)" -ForegroundColor Green
Write-Host "  wrapper : $installedWrapper"
Write-Host "  launcher: $installedVbs (wscript style 0 — no console flash)"
Write-Host "  next    : $((Get-ScheduledTaskInfo -TaskName $TaskName).NextRunTime)"
